### ISSUE TITLE
Add a CompatHelper action?

### ISSUE THREAD

**Issue by dkarrasch** [slimgroup/JOLI.jl#43]
I noticed JOLI.jl has a couple of outdated dependencies, for instance Flux.jl which is restricted to v0.12, but whose current version is v0.13.14. Perhaps it would make sense to add a CompatHelper workflow, to receive Project.toml updates via PRs, in which you can check if such an update is acceptable or not. See https://github.com/JuliaRegistries/CompatHelper.jl for more info.

**Comment by mloubout** [comment]
Flux.jl isn't a dependency, it's only a conditional one for testing but is not part of JOLI.jl  (only used in `rrule` test).

ComparHelper is already setup 
https://github.com/slimgroup/JOLI.jl/blob/master/.github/workflows/CompatHelper.yml

And all dependencies are up to date.

**Comment by dkarrasch** [comment]
Hm, should have checked before. Okay, but then why isn't NFFT.jl and Flux.jl up to date? I was working on a PR in Julia LinearAlgebra, which requires updates to very fundamental packages. The cap on Flux inhibits updating ArrayInterface.jl, which has updates that make it run smoothly both before and after that PR.

**Comment by dkarrasch** [comment]
Perhaps updating the CompatHelper script to https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml would help with the different dependency types.

**Comment by mloubout** [comment]
`NFFT.jl` newer versions have breaking changes, is on my list to fix.

For Flux there isn't really anything preventing upgrading it will check your link to make sure extra get caught as well.

Thanks for pointing it out

**Comment by mloubout** [comment]
Oh dang, it looks like CompatHelper stopped running due to inactivity, I'll  try to keep an eye on it in the future
